sudo: required
dist: trusty
language: python

before_install:
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ wily universe"
    - sudo apt-get update -q
    - sudo apt-get install shellcheck -y
python:
  - "2.7"
cache: pip
install: pip install pyflakes
script:
  - shellcheck ./3.3/bioc/zin2/postrun.sh ./3.2/bioc/zin1/postrun.sh ./manage-BioC-repos/3.3/prepareRepos.sh manage-BioC-repos/3.2/prepareRepos.sh
  - pyflakes *.py
  - python -c 'print "Finished static analysis"'
notifications:
  email:
    - brian@bioconductor.org
